### ISSUE TITLE
Timeout on big /get_blocks request

### ISSUE THREAD

**Issue by GlitchDino** [Niels-NTG/gdmc_http_interface#23]
Could a timeout parameter be added to /get_blocks? It times out at around a minute, which doesn't work for big requests (n>1 million)

**Comment by Niels-NTG** [comment]
As far as I can tell there's no way to control the timeout duration. When information is requested about parts of the world that haven't loaded on the Minecraft client yet, Minecraft first needs to generate this part of the world. This can take any amount of time. These request aren't able to time out on the server side. For testing I ran `GET http://localhost:9000/blocks?x=142&y=0&z=101&includeState=true&includeData=true&dx=2000&dy=2000&dz=2002`, which at the time of writing started 15 minutes ago and is still ongoing. Your request timing out around 1 minute of waiting is more likely a client-side problem, where the library doing the HTTP request has some default timeout value that's too low for this particular use case.

**Comment by Niels-NTG** [comment]
Update: after 25 minutes Minecraft ran out of memory and threw up an error message. The request itself didn't technically time out.

For a future update of GDMC-HTTP I could make a feature that detects when Minecraft reaches this state and timeout any pending requests. But it seems a bit of an edge-case to me.
