### ISSUE TITLE
Overwriting a container drops its contents even with `spawnDrops=false`

### ISSUE THREAD

**Issue by avdstaaij** [Niels-NTG/gdmc_http_interface#27]
Overwriting a container block (e.g. a chest) with a different block will cause its contents to be dropped, even when `spawnDrops` is set to the default value `false`. Based on the documentation of `spawnDrops`, this seems like unintended behavior.

Example request that produces this effect (sending two requests works too):
```
PUT localhost:9000/blocks

[
    {
        "x": 0,
        "y": 100,
        "z": 0,
        "id": "minecraft:chest",
        "data": "{Items: [{Slot: 13b, id: 'apple', Count: 1b}]}"
    },
    {
        "x": 0,
        "y": 100,
        "z": 0,
        "id": "minecraft:stone"
    }
]
```

Tested with:
- GDMC-HTTP 1.4.4
- Forge 48.1.0
- Minecraft 1.20.2

This behavior was not there in GDMC-HTTP 1.1.1, but I don't know which version introduced it (and I didn't feel like doing a binary search :P). I would guess it's 1.2.3 (which touched overwriting blocks with NBT data) or 1.4.0 (which optimized everything).

**Comment by Niels-NTG** [comment]
It seems likely this bug was introduced with the 1.4.0 update. Probably due to an order of operations issue.
